version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - ./pgdata:/var/lib/postgresql/data
